### ISSUE TITLE
i2c slave support?

### ISSUE THREAD

**Issue by MCUdude** [nerdralph/picoI2C#3]
picoI2C is already a great library for use with small microcontrollers like the ATtiny13. It doesn't do what it should, and compiled size is incredibly small for what it is. I know it's currently a master-only library, but are you planning somewhere in the future to add slave support as well?

The ATtiny13 would be an excellent device to act as an i2c slave, and there are several applications I know an ATtiny13 acting as an i2c slave would be very suitable; for instance in sensor applications.

**Comment by nerdralph** [comment]
I did put some thought into how to design it, but never came up with a good
design.  The timing constraints for the start/stop conditions are the
hardest part.  I'm sure I could write something that works, but not the
kind of code I'm proud of writing.

**Comment by nerdralph** [comment]
No plans, and unlikely it will become a priority.
